# coding: utf-8

"""
    Data Space Search Service

    The Search Service is a service of the Data Space Node, designed to process search queries and aggregate results from decentralized catalogs.

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ds_search_service.models.catalog_filters import CatalogFilters

class TestCatalogFilters(unittest.TestCase):
    """CatalogFilters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CatalogFilters:
        """Test CatalogFilters
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CatalogFilters`
        """
        model = CatalogFilters()
        if include_optional:
            return CatalogFilters(
                context = None
            )
        else:
            return CatalogFilters(
        )
        """

    def testCatalogFilters(self):
        """Test CatalogFilters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
