# coding: utf-8

# flake8: noqa
"""
    Template web service

    This is a template of a web service

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from ds_search_service.models.example_response import ExampleResponse
from ds_search_service.models.http_validation_error import HTTPValidationError
from ds_search_service.models.item import Item
from ds_search_service.models.validation_error import ValidationError
from ds_search_service.models.validation_error_loc_inner import ValidationErrorLocInner
