# Chart values for ds-search
replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent
  pullSecret: ""

# Optional: override the namespace; defaults to release namespace
namespace: nextgen

nameOverride: "ds-search"
fullnameOverride: "ds-search"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

container:
  command: ["uvicorn"]
  args: ["app.main:app", "--host", "0.0.0.0", "--port", "8080"]

livenessProbe:
  httpGet:
    path: /health-check/
    port: 8080
readinessProbe:
  httpGet:
    path: /health-check/
    port: 8080


service:
  type: ClusterIP
  port: 8080

env:
  - name: DS_SEARCH__POD_NAMESPACE
    value: "nextgen"
  - name: DS_SEARCH__SERVICE_NAME
    value: "ds-search"
  - name: DS_SEARCH__SERVICE_PORT
    value: "8080"
  - name: DS_SEARCH__CATALOG_SERVICE_URL
    value: "http://127.0.0.1:8081"
  - name: DS_SEARCH__DISCOVERY_TYPE
    value: "5.0"
  - name : LOG_LEVEL
    value: "INFO"

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

deploymentMode: daemonset  # or "deployment"

# Affinity block example (override if needed)
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist

# Optional nodeSelector & tolerations
nodeSelector: {}
tolerations: []

ingress:
  host: nextgen.hiro-develop.nl
  nodes:
    - nodeId: node1
    - nodeId: node2
    - nodeId: node3
