replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "search-service"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

container:
  command: ["uvicorn"]
  args: ["app.main:app", "--host", "0.0.0.0", "--port", "8080"]


service:
  type: ClusterIP
  port: 8080

resources: {}

livenessProbe:
  httpGet:
    path: /health-check/
    port: 8080
readinessProbe:
  httpGet:
    path: /health-check/
    port: 8080

env:
  - name: POD_NAMESPACE
    value: "nextgen"
  - name: SERVICE_NAME
    value: "search-service"
  - name: SERVICE_PORT
    value: "8000"
  - name: CATALOG_SERVICE_URL
    value: "http://catalog-service:8001"
  - name: REQUEST_TIMEOUT
    value: "5.0"
