# Chart values for ds-search
replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent
  pullSecret: ""

# Optional: override the namespace; defaults to release namespace
namespace: nextgen

nameOverride: "ds-search"
fullnameOverride: "ds-search"

## TODO: check do I need this or not
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

container:
  command: ["uvicorn"]
  args: ["app.main:app", "--host", "0.0.0.0", "--port", "8080"]

livenessProbe:
  httpGet:
    path: /health-check/
    port: 8080
readinessProbe:
  httpGet:
    path: /health-check/
    port: 8080


service:
  type: ClusterIP
  port: 8080

env:
## CRITICAL: fix this environment variables and check the discovery mechanism
  - name: DS_SEARCH__POD_NAMESPACE
    value: "nextgen"
  - name: DS_SEARCH__SERVICE_NAME
    value: "ds-search"
  - name: DS_SEARCH__SERVICE_PORT
    value: "8080"
  - name: DS_SEARCH__CATALOG_SERVICE_URL
    value: "http://ds-catalog:8081"
  - name: DS_SEARCH__REQUEST_TIMEOUT
    value: "5.0"
  - name : LOG_LEVEL
    value: "INFO"

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

deploymentMode: deployment  # or "daemonset"


# Optional nodeSelector & tolerations
nodeSelector: {}
tolerations: []

ingress:
  enabled: false
  host: nextgen.hiro-develop.nl
  nodes:
    - nodeId: hus
    - nodeId: ki
    - nodeId: uva

## Update this according to the desired node
nodeSelector:
  role: node-label

## To control the metics on development
metrics:
  enabled: false

# TODO: Remove this and delete cluster role file later after testing
clusterRole:
  enabled: false
